[versions]
compottie = "1.0.0-beta02"
kotlin="1.9.21"
dokka="1.9.0"
compose="1.5.11"
androidGradlePlugin = "8.1.1"
lottie-android="6.1.0"

[libraries]
lottie-android = { module ="com.airbnb.android:lottie-compose", version.ref = "lottie-android" }


[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id ="org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }